language: java
sudo: required

services:
  - mongodb
  - redis-server

before_script:
  - mongo travis --eval 'db.createUser({ user:"travis", pwd:"travis", roles:["readWrite"] });'

matrix:
  fast_finish: true

  include:
  - jdk: oraclejdk8

  allow_failures:
  - jdk: oraclejdk9
    addons:
      apt:
        packages:
          - oracle-java9-installer

notifications:
  email: false
